// Generated by CoffeeScript 1.6.3
$(function() {
  $.panels = function(toggle) {
    if (toggle) {
      if ($('.panel').hasClass(toggle)) {
        return $('.panel').removeClass(toggle);
      } else {
        return $('.panel').addClass(toggle);
      }
    } else {
      $('[data-toggle=slide]').click(function() {
        var dir, target;
        target = $($(this).attr('data-target'));
        dir = target.hasClass('panel-left') ? 'right' : 'left';
        if (target.hasClass(dir)) {
          $('.panel.panel-center').removeClass(dir);
          return target.removeClass(dir);
        } else {
          $('.panel.panel-center').addClass(dir);
          return target.addClass(dir);
        }
      });
      return $('.panel:not(.panel-center) [data-toggle^="tab"]').click(function() {
        $('.panel.in').removeClass('in');
        return $('.panel.panel-center').scrollTop(0);
      });
    }
  };
  return $.panels();
});
